# Uncomment the next line to define a global platform for your project
 platform :ios, ’10.0’

target 'Freely Market' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'PayPal-iOS-SDK'
  # Pods for Freely Market

  target 'Freely MarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Freely MarketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
